update run-regression script

diff --git a/exec/run-regression b/exec/run-regression
--- a/exec/run-regression
+++ b/exec/run-regression
@@ -5,14 +5,16 @@ export PATH="${GOPATH}/bin":$PATH
 
 ERROR_CODE=1
 
-# run crypto
-run-crypto
+if [ $1 != 'bm_only' ]; then
+    # run crypto
+    run-crypto
 
-# setup bitmarkd if bitmarkd config not exist
-setup-bitmarkd
-if [ $? -ne 0 ]; then
-    printf "\nsetup bitmarkd fail...abort\n"
-    exit $ERROR_CODE
+    # setup bitmarkd if bitmarkd config not exist
+    setup-bitmarkd
+    if [ $? -ne 0 ]; then
+        printf "\nsetup bitmarkd fail...abort\n"
+        exit $ERROR_CODE
+    fi
 fi
 
 # run bitmarkd
@@ -23,8 +25,10 @@ do
     cd "${HOME}/.config/bitmarkd${number}"
     nohup bitmarkd --config-file="bitmarkd${number}.conf" start >/dev/null 2>&1 &
 
-    # wait for bitmarkd to initialize tcp
-    sleep 90
+    # wait for bitmarkd to initialize tcp, only for 3, 4, 5
+    if [ $number != "1" ]; then
+        sleep 90
+    fi
 done
 
 # stop existing running recorderd
@@ -55,7 +59,6 @@ do
     sleep 10
 done
 printf "recorderd start success\n"
-
 cd - 1
 
 start_time=""
@@ -80,11 +83,11 @@ do
     for number in "${array[@]}"
     do
         normal_mode=$(curl -s -k "https://${local}:2${number}31/bitmarkd/details" | jq | grep -c Normal)
-    if [ $normal_mode -ne 0 ]; then
-        printf "\nnode ${number} in Normal mode, cli port 2${number}30, https port 2${number}31\n"
-        calculate_time
-        break 2                 # break 2 levels of loop
-    fi
+        if [ $normal_mode -ne 0 ]; then
+            printf "\nnode ${number} in Normal mode, cli port 2${number}30, https port 2${number}31\n"
+            calculate_time
+            break 2                 # break 2 levels of loop
+        fi
     done
     printf "waiting nodes to sync...\n"
     sleep 5
